// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'matrix.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

RustUrl? parseRustUrl({required String url}) =>
    RustLib.instance.api.crateApiUtilParseRustUrl(url: url);

bool isRustUrlHttps({required RustUrl url}) =>
    RustLib.instance.api.crateApiUtilIsRustUrlHttps(url: url);
